from typing import Any

from .base import BaseAPI

class ConfigurationsAPI(BaseAPI):
    def get_configs(self, project_id: int) -> list[dict[str, Any]]: ...
    def add_config_group(
        self, project_id: int, name: str
    ) -> dict[str, Any]: ...
    def add_config(
        self, config_group_id: int, name: str
    ) -> dict[str, Any]: ...
    def update_config_group(
        self, config_group_id: int, name: str
    ) -> dict[str, Any]: ...
    def update_config(self, config_id: int, name: str) -> dict[str, Any]: ...
    def delete_config_group(self, config_group_id: int) -> dict[str, Any]: ...
    def delete_config(self, config_id: int) -> dict[str, Any]: ...
