from typing import Any

from .base import BaseAPI

class LabelsAPI(BaseAPI):
    def get_label(self, label_id: int) -> dict[str, Any]: ...
    def get_labels(self, project_id: int) -> list[dict[str, Any]]: ...
    def add_label(
        self, project_id: int, name: str, color: str | None = ...
    ) -> dict[str, Any]: ...
    def update_label(self, label_id: int, **kwargs: Any) -> dict[str, Any]: ...
    def delete_label(self, label_id: int) -> dict[str, Any]: ...
