from typing import Any

from .base import BaseAPI as BaseAPI

__all__ = ["LabelsAPI"]

class LabelsAPI(BaseAPI):
    def get_label(self, label_id: int) -> dict[str, Any]: ...
    def get_labels(self, project_id: int) -> list[dict[str, Any]]: ...
    def add_label(self, project_id: int, title: str) -> dict[str, Any]: ...
    def update_label(self, label_id: int, **kwargs: Any) -> dict[str, Any]: ...
    def delete_label(self, label_id: int) -> dict[str, Any]: ...
