from typing import Any

from .base import BaseAPI as BaseAPI

class UsersAPI(BaseAPI):
    def get_user(self, user_id: int) -> dict[str, Any]: ...
    def get_users(self) -> list[dict[str, Any]]: ...
    def get_current_user(self) -> dict[str, Any]: ...
    def get_user_by_email(self, email: str) -> dict[str, Any]: ...
