#!/usr/bin/env python3
"""
Script to generate documentation for the TestRail API module using pdoc.
"""
import subprocess
import sys
from pathlib import Path


def check_pdoc_available() -> bool:
    """Check if pdoc is available in the current environment."""
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pdoc", "--version"],
            capture_output=True,
            text=True,
        )
        return result.returncode == 0
    except Exception:
        return False


def get_version() -> str:
    """Get the current version from the module."""
    try:
        # Add src to path to import the module
        src_path = Path(__file__).parent.parent / "src"
        sys.path.insert(0, str(src_path))
        
        from testrail_api_module import __version__
        return __version__
    except ImportError as e:
        print(f"❌ Error importing version: {e}")
        sys.exit(1)


def create_version_file(project_root: Path, version: str) -> None:
    """Create a version file for pdoc to include in documentation."""
    version_file = project_root / "src" / "testrail_api_module" / "_version.py"
    
    version_content = f'''"""
Version information for the TestRail API module.
This file is auto-generated by the documentation generation script.
"""

__version__ = "{version}"
"""
The current version of the TestRail API module.
"""

VERSION = __version__
"""
The current version of the TestRail API module.
"""
'''
    
    with open(version_file, 'w') as f:
        f.write(version_content)
    
    print(f"📝 Created version file: {version_file}")


def cleanup_version_file(project_root: Path) -> None:
    """Remove the temporary version file."""
    version_file = project_root / "src" / "testrail_api_module" / "_version.py"
    if version_file.exists():
        version_file.unlink()
        print(f"🧹 Cleaned up version file: {version_file}")


def main() -> None:
    """Generate documentation using pdoc."""
    # Check if pdoc is available
    if not check_pdoc_available():
        print("❌ pdoc is not installed or not available in the current environment.")
        print("\nTo install it, run one of the following:")
        print("  uv sync --extra dev")
        print("  uv pip install --extra dev")
        print("  uv run --with pdoc python utilities/generate_docs.py")
        sys.exit(1)
    
    # Get the project root directory (utilities/../)
    project_root = Path(__file__).parent.parent
    
    # Get current version
    version = get_version()
    print(f"📦 Current version: {version}")
    
    # Create version file for documentation
    create_version_file(project_root, version)
    
    # Remove existing docs directory
    docs_dir = project_root / "docs"
    if docs_dir.exists():
        print("Removing existing docs directory...")
        subprocess.run(["rm", "-rf", str(docs_dir)], check=True)

    # Generate new documentation
    print("Generating documentation with pdoc...")
    try:
        subprocess.run(
            [
                sys.executable,
                "-m",
                "pdoc",
                "--output-directory",
                str(docs_dir),
                "--docformat",
                "google",
                "--show-source",
                "--search",
                "--footer-text",
                f"TestRail API Module v{version}",
                str(project_root / "src" / "testrail_api_module"),
            ],
            check=True,
        )
        print("✅ Documentation generated successfully!")
        print(f"📁 Documentation is available in: {docs_dir}")
        print(
            f"🌐 Open {docs_dir / 'testrail_api_module' / 'index.html'} "
            f"in your browser to view it."
        )
    except subprocess.CalledProcessError as e:
        print(f"❌ Error generating documentation: {e}")
        if e.returncode == 1 and "No module named pdoc" in str(e):
            print("\n💡 Tip: Install pdoc with: uv sync --extra dev")
        sys.exit(1)
    except FileNotFoundError as e:
        print(f"❌ Error: {e}")
        print("\n💡 Tip: Make sure pdoc is installed. Run: uv sync --extra dev")
        sys.exit(1)
    finally:
        # Clean up the temporary version file
        cleanup_version_file(project_root)


if __name__ == "__main__":
    main()
